### ISSUE TITLE
AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext

### ISSUE THREAD

**Issue by kaikun213** [graphql-java-kickstart/samples#2]
I am using the proposed solution to set the authentication object in the Spring Security Context.

It works fine, but later received messages do not authenticate anymore and when a method which requires authentication due to annotations such as @PreAuthorize are invoked it throws the error:

```
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
```

And checking confirms that the Authentication Object is null.

I am wondering why this happens. I am using a JWT token in the onConnect method:

```

PreAuthenticatedAuthenticationJsonWebToken auth = PreAuthenticatedAuthenticationJsonWebToken.usingToken(tokenWithoutPrefix);
SecurityContextHolder.getContext().setAuthentication(auth);
```
Instead of username, password.

This thread suggests that the Token would need some authorities:
https://stackoverflow.com/questions/45405332/websocket-authentication-and-authorization-in-spring/45405333#45405333

However, the authentication usually works fine, it just does not persist over time while the websocket is open.

This post suggests that we need a websocket security configuration: https://stackoverflow.com/questions/47585025/spring-security-websockets-authentication-not-set-for-frame-handler

Any idea how to fix that? Or anyone encountered the same with grapphql subscriptions?

**Comment by oliemansm** [comment]
Could it be a Thread issue? The onConnect is on a different Thread than the later ones causing the Authentication object from the onConnect to not be available to those later ones. I don't know your code so I can't really say if that's the case here or not.

**Comment by kaikun213** [comment]
Yes, I think that is the issue:

```
2019-11-18 10:48:56.424  INFO 1 --- [nio-5000-exec-3] c.a.s.s.api.JwtAuthenticationProvider    : Authenticated with jwt with scopes [openid, profile, email]
2019-11-18 10:48:56.456  INFO 1 --- [nio-5000-exec-5] c.a.s.s.api.JwtAuthenticationProvider    : Authenticated with jwt with scopes [openid, profile, email]
2019-11-18 10:48:57.348  WARN 1 --- [nio-5000-exec-4] g.e.SimpleDataFetcherExceptionHandler    : Exception while fetching data (/fetchData) : An Authentication object was not found in the SecurityContext
```

They are handled by different executors. How could one prevent that? I guess Spring is responsible for handling the thread scheduling for the websocket connection.

**Comment by oliemansm** [comment]
Try the following. Have your listener return your `Authentication` in the `Optional`:
```java
public Optional<Object> onConnect(Object payload) {
    log.debug("onConnect with payload {}", payload.getClass());
    String token = ((Map<String, String>) payload).get("authToken");
    log.info("Token: {}", token);
    return Optional.of(new UsernamePasswordAuthenticationToken(token, null));
  }
```
Then in your subscription resolver method get a hold of it from the context instead of from the `SecurityContext` and explicitly set it there:
```java
Publisher<Integer> hello(DataFetchingEnvironment env) {
    GraphQLWebSocketContext context = env.getContext();
    Optional<Authentication> authentication = Optional.ofNullable(context.getSession())
        .map(Session::getUserProperties)
        .map(props -> props.get(ApolloSubscriptionConnectionListener.CONNECT_RESULT_KEY))
        .map(Authentication.class::cast);
    log.info("Subscribe to publisher with authentication: {}", authentication);
    SecurityContextHolder.getContext().setAuthentication(authentication);
    return publisher;
  }
```

**Comment by oliemansm** [comment]
I'm assuming this solved your issue.

**Comment by karmakard-lh** [comment]
remove **addFilters = false** from annotation **@AutoConfigureMockMvc(addFilters = false)**
