### ISSUE TITLE
webflux HelloQuery.java

### ISSUE THREAD

**Issue by pokebadgerswithspoon** [graphql-java-kickstart/samples#3]
Hello.

https://github.com/graphql-java-kickstart/samples/blob/acc70ff69d4776456fd148cb0513a8f2617dbc32/spring-boot-webflux/src/main/java/webflux/HelloQuery.java

Is there a way to make query resolver to return a Mono?

**Comment by oliemansm** [comment]
That’s already supported. Have you tried...?

Groeten,
Michiel
________________________________
Van: Lauri <notifications@github.com>
Verzonden: Saturday, February 29, 2020 2:23:57 PM
Aan: graphql-java-kickstart/samples <samples@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [graphql-java-kickstart/samples] webflux HelloQuery.java (#3)


Hello.

https://github.com/graphql-java-kickstart/samples/blob/acc70ff69d4776456fd148cb0513a8f2617dbc32/spring-boot-webflux/src/main/java/webflux/HelloQuery.java

Is there a way to make query resolver to return a Mono?

**Comment by pokebadgerswithspoon** [comment]
Yes, but with strange result.
package com.icantfeelmylegs.sharebingo.graphql;
```java
import com.coxautodev.graphql.tools.GraphQLQueryResolver;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Mono;

@Component
class HelloQuery implements GraphQLQueryResolver {

  public Mono<String> hello() {
      return Mono.just("Hello world. This is webflux");
  }
}
```

This results in
```json
 "data": {
    "hello": "MonoJust"
  }
```

**Comment by pokebadgerswithspoon** [comment]
Thanks for update: https://github.com/graphql-java-kickstart/samples/commit/054492d5036b9bc2398bf970c0bc17262dd5fc0d#diff-4ec276d100cf531becadd23fecb2575c

Now I get it, the ingredient was to convert Mono to CompletableFuture, it works indeed.
