### ISSUE TITLE
Unable to run spring-boot-webflux sample

### ISSUE THREAD

**Issue by bbedrin** [graphql-java-kickstart/samples#6]
Hi, 

I was trying to implement the graphql-kickstart-spring-boot-starter-webflux and kept running into the below error. I tried cloning the sample spring-boot-webflux repo, but ran into the same issue as well.

```
Parameter 1 of method webSocketHandlerMapping in graphql.kickstart.spring.webflux.boot.GraphQLSpringWebfluxAutoConfiguration required a bean of type 'graphql.kickstart.spring.webflux.ReactiveWebSocketSubscriptionsHandler' that could not be found.

Action:

Consider defining a bean of type 'graphql.kickstart.spring.webflux.ReactiveWebSocketSubscriptionsHandler' in your configuration.
```

When I then try to implement a bean of ReactiveWebSocketSubscriptionsHandler, it resolves the startup error but doesn't start 

```
@Bean
	public ReactiveWebSocketSubscriptionsHandler reactiveWebSocketSubscriptionsHandler(ReactiveSubscriptionsProtocolFactory subscriptionProtocolFactory) {
		return new ReactiveWebSocketSubscriptionsHandler(subscriptionProtocolFactory);
	}
```

But it doesn't start up the /graphql or /subscription endpoints.

```
2020-05-24 21:41:42.289  INFO 23511 --- [           main] webflux.WebfluxApplication               : No active profile set, falling back to default profiles: default
2020-05-24 21:41:43.596  INFO 23511 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2020-05-24 21:41:43.606  INFO 23511 --- [           main] webflux.WebfluxApplication               : Started WebfluxApplication in 1.493 seconds (JVM running for 2.156)
```

Am I missing something else that isn't documented?

**Comment by oliemansm** [comment]
The bean is created by the starter automatically, you shouldn't have to create that manually. I just tried the sample and it's working fine for me. Main points to check are:

1. You have the same dependencies the sample is using
2. You have a GraphQL SDL file in your classpath with graphqls extension defining your schema

Those things are configured correctly in the sample project though, so should work.

**Comment by bbedrin** [comment]
Hi,

I did a fresh install of the sample and still cant run the application.

Where is the bean registered? I took a look for it in the main repository and cannot find it. https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/master/graphql-kickstart-spring-boot-autoconfigure-webflux/src/main/java/graphql/kickstart/spring/webflux/boot/GraphQLSpringWebfluxAutoConfiguration.java

**Comment by oliemansm** [comment]
That's very strange... It uses component scan with a base package to find this bean automatically here https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/0ab682cefb2358c8c7fb5473e84ee9e45fd6be12/graphql-kickstart-spring-boot-autoconfigure-webflux/src/main/java/graphql/kickstart/spring/webflux/boot/GraphQLSpringWebfluxAutoConfiguration.java#L54.

**Comment by morrowyn** [comment]
I'm running into the same error using the 7.1.0-SNAPSHOT. I don't have this problem with the 7.0.2-SNAPSHOT though.

**Comment by sseep** [comment]
I downloaded project (https://github.com/graphql-java-kickstart/samples/tree/master/spring-boot-webflux)[https://github.com/graphql-java-kickstart/samples/tree/master/spring-boot-webflux] and
Doesn't modify any file. 
Run spring-boot-webflux sample still got error.
```
Description:

Parameter 1 of method webSocketHandlerMapping in graphql.kickstart.spring.webflux.boot.GraphQLSpringWebfluxAutoConfiguration required a bean of type 'graphql.kickstart.spring.webflux.ReactiveWebSocketSubscriptionsHandler' that could not be found.


Action:

Consider defining a bean of type 'graphql.kickstart.spring.webflux.ReactiveWebSocketSubscriptionsHandler' in your configuration.
```

**Comment by Racv** [comment]
I am also facing similar issue.. I am using version 7.1.0 and I am getting /graphql not found.. any suggestion on how to solve this?

**Comment by kejistan** [comment]
This seems related to https://github.com/graphql-java-kickstart/graphql-spring-boot/commit/d865b8cee499685ac2e155915cff576cc424bc3c Like @Racv I'm also not seeing my /graphql endpoint. I'm defining my own `graphql.schema.GraphQLSchema` bean but the autoconfiguration report lists `GraphQLSpringWebfluxAutoConfiguration` in the negative matches section:

```
GraphQLSpringWebfluxAutoConfiguration:
   Did not match:
      - @ConditionalOnBean (types: graphql.schema.GraphQLSchema; SearchStrategy: all) did not find any beans of type graphql.schema.GraphQLSchema (OnBeanCondition)
   Matched:
      - @ConditionalOnBean (types: graphql.schema.GraphQLSchema; SearchStrategy: all) found bean 'graphQLSchema' (OnBeanCondition)
```

**Comment by conanchen** [comment]
> I'm running into the same error using the 7.1.0-SNAPSHOT. I don't have this problem with the 7.0.2-SNAPSHOT thoug

 7.1.0-SNAPSHOT the same

**Comment by aymanmoukhtar** [comment]
Any updates on this?

**Comment by Tandolf** [comment]
i am trying out the webflux 7.1.0 release, and i am getting this error.

Anyone that has any workaround?

**Comment by joaomlneto** [comment]
> I'm running into the same error using the 7.1.0-SNAPSHOT. I don't have this problem with the 7.0.2-SNAPSHOT though.

Same problem, similar fix using the releases in the maven central repository.
Tried using release `7.1.0` and got this error. Using release `7.0.1` works fine.

**Comment by vojtapol** [comment]
We accept PRs if anyone is willing to fix this.

**Comment by pokebadgerswithspoon** [comment]
Seems this fixes the issue, at least spring-boot app starts with following config applied
```
@ComponentScans({
     @ComponentScan("graphql.kickstart.tools.boot"),
     @ComponentScan("graphql.kickstart.spring.webflux")
})
```
Will it be a good PR with the snippet applied to `GraphQLSpringWebfluxAutoConfiguration.java`?

**Comment by pokebadgerswithspoon** [comment]
P.s. This issue seems to be relevant https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/428

**Comment by oliemansm** [comment]
I've implemented @kejistan fix which works like a charm on my end (was able to reproduce it too first with 7.1.0). It's available for now in the Snapshot release of graphql-spring-boot 7.2.0-SNAPSHOT.
